# Generated by Django 4.0.5 on 2022-08-04 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_rename_user_usersegregation_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersegregation',
            old_name='user',
            new_name='username',
        ),
    ]
