# Generated by Django 4.0.5 on 2022-08-05 04:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_shift_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shift',
            name='user',
        ),
        migrations.AddField(
            model_name='shift',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.usersegregation'),
        ),
    ]
