# Generated by Django 4.0.5 on 2022-08-05 14:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import nt


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0009_remove_shift_user_shift_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=200)),
                ('cost', models.IntegerField(blank=True, null=True)),
                ('rating', models.IntegerField(blank=True, null=nt.truncate)),
                ('description', models.TextField(blank=True, max_length=400, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='usersegregation',
            name='username',
        ),
        migrations.DeleteModel(
            name='Shift',
        ),
        migrations.DeleteModel(
            name='UserSegregation',
        ),
        migrations.AddField(
            model_name='cart',
            name='product',
            field=models.ManyToManyField(to='base.product'),
        ),
    ]
