# Generated by Django 4.0.5 on 2022-08-05 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_cart_product_remove_usersegregation_username_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='quantity',
        ),
    ]
